#!/bin/sh

source `dirname $0`/properties

cd ${SELFLOCATION}
for i in *.po ; do
	LNG=`echo $i | sed -e 's/\.po$//g'`
	echo Creating class for language \"$LNG\"
	JAVAC=javac msgfmt -d . --java2 --resource=${CLASSPATH}.Messages_$LNG $i
	if [ $? != 0 ] ; then exit 1; fi
done
mv ${CLASSDIR}/Messages_*.class ${SRCLOCATION}/${CLASSDIR}
rm -fr com
